# Generated by Django 5.1.7 on 2025-05-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleantext',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
