# Generated by Django 5.1.7 on 2025-05-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0002_cleantext_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_config',
            fields=[
                ('sysdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sysdb_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sysdb_data', models.JSONField(default=dict)),
            ],
        ),
    ]
